site_name: OpenShock
docs_dir: docs
site_url: https://openshock.org/
repo_url: https://github.com/OpenShock/Wiki

nav:
  - Home: index.md
  - Safety: safety/safety-rules.md
  - Guides:
    - Quickstart:
      - quickstart/what-you-need.md
      - quickstart/buying-guide.md
    - Openshock:
      - guides/openshock-how-to-flash-your-board.md
      - guides/openshock-first-setup.md
      - guides/openshock-how-to-update.md
      - guides/shocklink-sharelinks.md
      - guides/shocklink-sharecodes.md
    - ShockOsc:
      - guides/shockosc-basic-new.md
      - guides/shockosc-avatar-setup-vrc.md
      - guides/shockosc-avatar-setup-cvr.md 
  - Hardware:
    # - hardware/buying-guide.md
    - Shockers:
      - hardware/shockers/index.md
      - hardware/shockers/caixianlin.md
      - hardware/shockers/pettrainer.md
    - Remotes:
      - hardware/remotes/identifying.md
    - Boards:
      - 'hardware/boards/index.md'
      # - Knockoffs:
      #   - 'hardware/boards/china/esp32s3-dorx.md'
      - Pishock:
        - 'hardware/boards/pishock/2023-pishock.md'
        - 'hardware/boards/pishock/2021q3-lite.md'
        - 'hardware/boards/pishock/2021q1-plus.md'
      - Seeed:
        - hardware/boards/seeed/xiao-esp32s3.md
      - Wemos:
        - 'hardware/boards/wemos/d1-mini-esp32.md'
        - 'hardware/boards/wemos/lolin-s2-mini.md'
        - 'hardware/boards/wemos/lolin-s3.md'
    - Radio:
      - hardware/radio/index.md
  - Vendors:
    - Hardware:
      - 'vendors/hardware/index.md'
      - Europe:
        - 'vendors/hardware/luc.md'
        - 'vendors/hardware/bosjesman.md'
        - 'vendors/hardware/HentaiHeaven.md'
    - 'vendors/software.md'
  - Do-it-yourself:
    - Hardware:
      - diy/prerequisites.md
      - diy/assembling.md
    - Selfhosting:
      - 'selfhosting/index.md'
  - 'contributing/contributing.md'

theme:
  name: material
  logo: static/branding/Icon.svg
  favicon: static/branding/Icon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate
  custom_dir: overrides
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - tags:
      enabled: true
      
extra:
  # Tag definitions for tagging pages.
  tags:
    selfhosting: banana

  # Social links rendered in the footer.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AHcCbXbEcF
      name: Discord

    - icon: fontawesome/brands/github
      link: https://github.com/OpenShock
      name: GitHub
